# Generated by Django 5.1.3 on 2025-11-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('WEB', 'Web Development'), ('ML', 'Machine Learning'), ('DSN', 'Design'), ('MKT', 'Marketing'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('link', models.URLField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='projects', to='team.teammember')),
            ],
            options={
                'ordering': ['-start_date', 'title'],
            },
        ),
    ]
