# Generated by Django 5.1.3 on 2025-11-28 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teammember_description_alter_teammember_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of technologies for the project', size=None),
        ),
    ]
