# Generated by Django 5.1.3 on 2025-12-07 12:00

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_project_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
