# Generated by Django 5.1.3 on 2025-11-23 13:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of skills for the team member', size=None),
        ),
    ]
