# Generated by Django 5.1.3 on 2025-11-23 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_teammember_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event', models.CharField(blank=True, help_text='Hackathon, competition, conference name', max_length=150)),
                ('date', models.DateField(blank=True, null=True)),
                ('award', models.CharField(blank=True, help_text='Prize, rank, or award title', max_length=150)),
                ('link', models.URLField(blank=True, help_text='Optional link to certificate or event page')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='team.teammember')),
            ],
            options={
                'ordering': ['-date', 'title'],
            },
        ),
    ]
