# Generated by Django 5.1.3 on 2025-11-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='achievement_images/'),
        ),
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='education_images/'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='work_experience_images/'),
        ),
    ]
